global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: mmp-observability-hook

receivers:
  - name: mmp-observability-hook
    webhook_configs:
      - url: 'http://host.docker.internal:4000/v1/observability/alert-hook'
        send_resolved: true
        max_alerts: 20
